Instalação
JsLadiesBR/tutorial-inicante pull request #3
Opened 2017-09-17 23:34 UTC by letuche

Começo do capítulo de Instalação para o tutorial.
(tomei uma surra do git, espero que esteja tudo ok, senão me avisem pls)

2017-09-18 03:11 UTC, hi-hi-ray requested changes

2017-09-18 03:11 UTC, hi-hi-ray commented on tutorial/INSTALL.md
>  ## Preparando o Ambiente
Falta só como preparar o ambiente. =]

2017-09-18 03:12 UTC, hi-hi-ray commented on tutorial/INSTALL.md
> +###Linux baseado em Debian ou Ubuntu:
Por favor, adiciona um espaço entre o ###  e o texto "Linux baseado em Debian ou Ubuntu:" =]

2017-09-18 03:13 UTC, hi-hi-ray requested changes

2017-09-18 03:13 UTC, hi-hi-ray commented on tutorial/INSTALL.md
> +###Linux baseado em Debian ou Ubuntu:
Outra coisa que seria bom, é por a instalação em outro S.O. É possível achar tutorial de vários S.O =]

2017-09-24 01:21 UTC, hi-hi-ray commented on tutorial/INSTALL.md
>  ## Preparando o Ambiente
- Escolher um editor de texto.
- Baixar o Mozilla, e por em modo desenvolvedor.
- Por as extensões no navegador da Mozilla (Firebug).
- Configurar o Node.js nas configurações globais (windows).

2019-08-22 17:55 UTC, letuche commented
Pessoal, na época em que eu fiz esse PR nem sabia usar git ainda! Haha
Esta contribuição ainda é necessária, ou posso fechar? O tutorial ainda está sendo elaborado?

2019-09-25 19:40 UTC, letuche commented
@hi-hi-ray, faz sentido ainda recuperar este PR? Ou posso fechar?

2024-04-22 15:03 UTC, closed without merging